update steps for api key, fix typo
krishnavelu/alice_blue pull request #283
Opened 2021-05-14 07:52 UTC by ksyko

2021-05-14 12:14 UTC, krishnavelu requested changes
Didn't know I have these many typos. Thanks for correcting it.
Please create a pull request (after fixing my review comments) to develop branch, not directly to master branch.
I'll accept.

2021-05-14 12:14 UTC, krishnavelu commented on README.md
> +4. Enter 'App Name' as you like. Enter 'Redirect URI' as 'http://develop-api.aliceblueonline.com/'
Change this to `https://ant.aliceblueonline.com/plugin/callback`.
That is the default redirect_url of the library.

2021-05-14 12:14 UTC, krishnavelu commented on README.md
> +2. Create access_token using login_and_get_access_token() function  with your `username`, `password`, `2FA`, `app_id` and `api_secret`. Both 2FA should be same.
Add `If possible set both 2FA to 'a' as in example`

2021-05-14 13:41 UTC, ksyko commented
updated

2021-05-16 21:37 UTC, krishnavelu commented
![image](https://user-images.githubusercontent.com/38440742/118413449-6230fc00-b66d-11eb-9258-0c518213a100.png)

I don't want to see these commits in this PR.

2021-05-16 21:39 UTC, krishnavelu requested changes

2021-05-16 21:39 UTC, krishnavelu commented on README.md
> +2. Create access_token using login_and_get_access_token() function  with your `username`, `password`, `2FA`, `app_id` and `api_secret`. Both 2FA should be same.
I don't think this is resolved.

2021-05-16 21:55 UTC, krishnavelu commented
@ksyko No issues. I've added all your changes along with review comments in this issue #285.
Closing this PR.

2021-05-16 21:55 UTC, closed without merging